version: '3.1'
services:
  api:
    container_name: linkly-docker
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment: 
      MYSQL_DATABASE: linkly_db
      MYSQL_ROOT_PASSWORD: linkly
    volumes: 
      - ../mysql_data:/var/lib/mysql
      